+ NGPUS=2
+ PY_ARGS='--cfg_file cfgs/exp20_gen.yaml --tcp_port 18889 --max_ckpt_save_num 10 --workers 1 --extra_tag fold_0'
+ python -m torch.distributed.launch --nproc_per_node=2 train.py --launcher pytorch --cfg_file cfgs/exp20_gen.yaml --tcp_port 18889 --max_ckpt_save_num 10 --workers 1 --extra_tag fold_0
/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/train.py", line 6, in <module>
    from test import repeat_eval_ckpt
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/test.py", line 13, in <module>
    from eval_utils import eval_utils
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/eval_utils/eval_utils.py", line 11, in <module>
    from pcdet.utils.loss_utils import rbbox_to_corners, rinter_area_compute
ImportError: cannot import name 'rbbox_to_corners' from 'pcdet.utils.loss_utils' (/home/liangao/projects/AW/openpcdet/pcdet/utils/loss_utils.py)
Traceback (most recent call last):
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/train.py", line 6, in <module>
    from test import repeat_eval_ckpt
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/test.py", line 13, in <module>
    from eval_utils import eval_utils
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/eval_utils/eval_utils.py", line 11, in <module>
    from pcdet.utils.loss_utils import rbbox_to_corners, rinter_area_compute
ImportError: cannot import name 'rbbox_to_corners' from 'pcdet.utils.loss_utils' (/home/liangao/projects/AW/openpcdet/pcdet/utils/loss_utils.py)
WARNING:torch.distributed.elastic.agent.server.api:Received 2 death signal, shutting down workers
Traceback (most recent call last):
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 236, in launch_agent
    result = agent.run()
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 850, in _invoke_run
    time.sleep(monitor_interval)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 60, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 94577 got signal: 2
+ NGPUS=2
+ PY_ARGS='--cfg_file cfgs/exp20_gen.yaml --tcp_port 18889 --max_ckpt_save_num 10 --workers 1 --extra_tag fold_0'
+ python -m torch.distributed.launch --nproc_per_node=2 train.py --launcher pytorch --cfg_file cfgs/exp20_gen.yaml --tcp_port 18889 --max_ckpt_save_num 10 --workers 1 --extra_tag fold_0
/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/train.py", line 6, in <module>
    from test import repeat_eval_ckpt
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/test.py", line 13, in <module>
    from eval_utils import eval_utils
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/eval_utils/eval_utils.py", line 11, in <module>
    from pcdet.utils.loss_utils import rbbox_to_corners, rinter_area_compute
ImportError: cannot import name 'rbbox_to_corners' from 'pcdet.utils.loss_utils' (/home/liangao/projects/AW/openpcdet/pcdet/utils/loss_utils.py)
Traceback (most recent call last):
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/train.py", line 6, in <module>
    from test import repeat_eval_ckpt
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/test.py", line 13, in <module>
    from eval_utils import eval_utils
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/eval_utils/eval_utils.py", line 11, in <module>
    from pcdet.utils.loss_utils import rbbox_to_corners, rinter_area_compute
ImportError: cannot import name 'rbbox_to_corners' from 'pcdet.utils.loss_utils' (/home/liangao/projects/AW/openpcdet/pcdet/utils/loss_utils.py)
WARNING:torch.distributed.elastic.agent.server.api:Received 2 death signal, shutting down workers
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 94804 closing signal SIGINT
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 94805 closing signal SIGINT
Traceback (most recent call last):
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 236, in launch_agent
    result = agent.run()
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 850, in _invoke_run
    time.sleep(monitor_interval)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 60, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 94801 got signal: 2
+ NGPUS=2
+ PY_ARGS='--cfg_file cfgs/exp20_gen.yaml --tcp_port 18889 --max_ckpt_save_num 10 --workers 1 --extra_tag fold_0'
+ python -m torch.distributed.launch --nproc_per_node=2 train.py --launcher pytorch --cfg_file cfgs/exp20_gen.yaml --tcp_port 18889 --max_ckpt_save_num 10 --workers 1 --extra_tag fold_0
/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/train.py", line 6, in <module>
    from test import repeat_eval_ckpt
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/test.py", line 13, in <module>
    from eval_utils import eval_utils
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/eval_utils/eval_utils.py", line 11, in <module>
    from pcdet.utils.loss_utils import rbbox_to_corners, rinter_area_compute
ImportError: cannot import name 'rbbox_to_corners' from 'pcdet.utils.loss_utils' (/home/liangao/projects/AW/openpcdet/pcdet/utils/loss_utils.py)
Traceback (most recent call last):
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/train.py", line 6, in <module>
    from test import repeat_eval_ckpt
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/test.py", line 13, in <module>
    from eval_utils import eval_utils
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/eval_utils/eval_utils.py", line 11, in <module>
    from pcdet.utils.loss_utils import rbbox_to_corners, rinter_area_compute
ImportError: cannot import name 'rbbox_to_corners' from 'pcdet.utils.loss_utils' (/home/liangao/projects/AW/openpcdet/pcdet/utils/loss_utils.py)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 94930) of binary: /home/liangao/anaconda3/envs/pcdet/bin/python
Traceback (most recent call last):
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-02-27_11:53:58
  host      : gpuser03
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 94931)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-02-27_11:53:58
  host      : gpuser03
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 94930)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
+ NGPUS=2
+ PY_ARGS='--cfg_file cfgs/exp20_gen.yaml --tcp_port 18889 --max_ckpt_save_num 10 --workers 1 --extra_tag fold_0'
+ python -m torch.distributed.launch --nproc_per_node=2 train.py --launcher pytorch --cfg_file cfgs/exp20_gen.yaml --tcp_port 18889 --max_ckpt_save_num 10 --workers 1 --extra_tag fold_0
/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/train.py", line 6, in <module>
    from test import repeat_eval_ckpt
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/test.py", line 13, in <module>
    from eval_utils import eval_utils
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/eval_utils/eval_utils.py", line 11, in <module>
    from pcdet.utils.loss_utils import rbbox_to_corners, rinter_area_compute
ImportError: cannot import name 'rbbox_to_corners' from 'pcdet.utils.loss_utils' (/home/liangao/projects/AW/openpcdet/pcdet/utils/loss_utils.py)
Traceback (most recent call last):
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/train.py", line 6, in <module>
    from test import repeat_eval_ckpt
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/test.py", line 13, in <module>
    from eval_utils import eval_utils
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/eval_utils/eval_utils.py", line 11, in <module>
    from pcdet.utils.loss_utils import rbbox_to_corners, rinter_area_compute
ImportError: cannot import name 'rbbox_to_corners' from 'pcdet.utils.loss_utils' (/home/liangao/projects/AW/openpcdet/pcdet/utils/loss_utils.py)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 100188) of binary: /home/liangao/anaconda3/envs/pcdet/bin/python
Traceback (most recent call last):
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-02-27_11:57:34
  host      : gpuser03
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 100189)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-02-27_11:57:34
  host      : gpuser03
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 100188)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
+ NGPUS=2
+ PY_ARGS='--cfg_file cfgs/exp20_gen.yaml --tcp_port 18889 --max_ckpt_save_num 10 --workers 1 --extra_tag fold_0'
+ python -m torch.distributed.launch --nproc_per_node=2 train.py --launcher pytorch --cfg_file cfgs/exp20_gen.yaml --tcp_port 18889 --max_ckpt_save_num 10 --workers 1 --extra_tag fold_0
/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/train.py", line 6, in <module>
    from test import repeat_eval_ckpt
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/test.py", line 13, in <module>
    from eval_utils import eval_utils
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/eval_utils/eval_utils.py", line 10, in <module>
    from ...pcdet.utils.loss_utils import rbbox_to_corners, rinter_area_compute
ImportError: attempted relative import beyond top-level package
Traceback (most recent call last):
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/train.py", line 6, in <module>
    from test import repeat_eval_ckpt
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/test.py", line 13, in <module>
    from eval_utils import eval_utils
  File "/home/liangao/projects/IA-SSD/cvae_uncertainty/eval_utils/eval_utils.py", line 10, in <module>
    from ...pcdet.utils.loss_utils import rbbox_to_corners, rinter_area_compute
ImportError: attempted relative import beyond top-level package
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 100566) of binary: /home/liangao/anaconda3/envs/pcdet/bin/python
Traceback (most recent call last):
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/liangao/anaconda3/envs/pcdet/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-02-27_11:59:09
  host      : gpuser03
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 100567)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-02-27_11:59:09
  host      : gpuser03
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 100566)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
